### PR TITLE
divided smoke and full tests into two parts

### PR DESCRIPTION
**Pull request by msakowicz**
This branch should be merged together with https://github.com/SecureTrading/js-payments/pull/887
I'll wait with merging this branch to not break other builds from js-payments repo

### CODE REVIEW

**Comment by james-simpson-ST** [comment]
Will this work with current master because it is using @smoke_test and @full_test tags. So maybe we want to keep those tags until we change the travis on the code to use the new tags?

**Comment by msakowicz** [comment]
> Will this work with current master because it is using @smoke_test and @full_test tags. So maybe we want to keep those tags until we change the travis on the code to use the new tags?


Yes, exactly, I've added the same note at the top of this PR :)

> This branch should be merged together with SecureTrading/js-payments#887
> I'll wait with merging this branch to not break other builds from js-payments repo

**Comment by james-simpson-ST** [comment]
> Yes, exactly, I've added the same note at the top of this PR :)
> 
> > This branch should be merged together with [SecureTrading/js-payments#887](https://github.com/SecureTrading/js-payments/pull/887)
> > I'll wait with merging this branch to not break other builds from js-payments repo

Won't this mean master would be broken though because master won't get those changes until the next release, if we keep the old tag names and add a maintenance task to remove the old tags after we have created 2.0.10 release we can merge this now and be backwards compatible with master

**Comment by msakowicz** [comment]
ah ok, we can do it in this way

**Pull request merged**
